// Seed Data for Jhankra Super League (JSL)

export const INITIAL_LEAGUES = [
  {
    id: "leg-jpl",
    code: "JPL",
    name: "JPL - Jhankra Premier League 2026",
    tagline: "The Flagship T20 League",
    category: "JPL",
    status: "COMING_SOON",
    entryFee: 1500,
    prizePool: "₹ 2,50,000",
    venue: "Jhankra Stadium Ground"
  },
  {
    id: "leg-jsl",
    code: "JSL",
    name: "JHANKRA SUPER LEAGUE 2026",
    tagline: "8 TEAM LEAGUE CRICKET TOURNAMENT",
    category: "JSL",
    status: "REGISTRATION_OPEN",
    teamEntryFee: 15000, // 15K
    playerEntryFee: 200,   // 200 Rupees for Player Entry
    prizeWinner: "35K",
    prizeRunners: "25K",
    auctionPurse: 8000,
    entryFeePortion: 7000,
    dates: "29, 30 & 31 AUGUST 2026",
    venue: "JHANKRA SCHOOL GROUND",
    ruleRestriction: "ONLY CHANDRAKONA TOWN PS PLAYERS ARE ALLOWED.",
    contactPerson: "PINTU",
    contactNumber: "89722144166",
    maxTeams: 8
  },
  {
    id: "leg-kpl",
    code: "KPL",
    name: "KPL - Kota Premier League 2026",
    tagline: "Kota Premier League",
    category: "KPL",
    status: "COMING_SOON",
    entryFee: 1000,
    prizePool: "₹ 1,80,000",
    venue: "Kota Sports Ground"
  }
];

export const INITIAL_TEAMS = [
  {
    id: "team-khirpai-hurricanes",
    leagueId: "leg-jsl",
    serialNo: 1,
    name: "KHIRPAI HURRICANES",
    shortCode: "KH",
    ownerName: "Arijit Ghosh (Mantu)",
    ownerPhone: "9083354758",
    captainName: "Arijit Ghosh",
    iconPlayerName: "Bijay Haldar",
    iconName: "Bijay Haldar",
    logoUrl: "assets/team_confirm_1_khirpai_hurricanes.jpg",
    teamLogoUrl: "assets/team_confirm_1_khirpai_hurricanes.jpg",
    registrationStatus: "APPROVED",
    paymentStatus: "APPROVED",
    purse: 8000,
    remainingPurse: 8000
  },
  {
    id: "team-aniket-xi",
    leagueId: "leg-jsl",
    serialNo: 2,
    name: "ANIKET XI",
    shortCode: "AXI",
    ownerName: "Uttam Ghosh",
    ownerPhone: "9321434719",
    captainName: "Uttam Ghosh",
    iconPlayerName: "Rahul Dev Roy (Rintu)",
    iconName: "Rahul Dev Roy",
    logoUrl: "assets/team_confirm_2_aniket_xi.jpg",
    teamLogoUrl: "assets/team_confirm_2_aniket_xi.jpg",
    registrationStatus: "APPROVED",
    paymentStatus: "APPROVED",
    purse: 8000,
    remainingPurse: 8000
  },
  {
    id: "team-srs-brothers",
    leagueId: "leg-jsl",
    serialNo: 3,
    name: "SRS BROTHERS",
    shortCode: "SRS",
    ownerName: "RAJA",
    ownerPhone: "9382582221",
    captainName: "RAJA",
    iconPlayerName: "Tapas Biswas",
    iconName: "Tapas Biswas",
    logoUrl: "assets/team_confirm_3_srs_brothers.jpg",
    teamLogoUrl: "assets/team_confirm_3_srs_brothers.jpg",
    registrationStatus: "APPROVED",
    paymentStatus: "APPROVED",
    purse: 8000,
    remainingPurse: 8000
  },
  {
    id: "team-shiv-shakti-ekadash",
    leagueId: "leg-jsl",
    serialNo: 4,
    name: "SHIV SHAKTI EKADASH",
    shortCode: "SSE",
    ownerName: "Debiprasad Pramanik",
    ownerPhone: "9800000004",
    captainName: "Debiprasad Pramanik",
    iconPlayerName: "Subham Sir",
    iconName: "Subham Sir",
    logoUrl: "assets/team_confirm_4_shiv_shakti_ekadash.jpg",
    teamLogoUrl: "assets/team_confirm_4_shiv_shakti_ekadash.jpg",
    registrationStatus: "APPROVED",
    paymentStatus: "APPROVED",
    purse: 8000,
    remainingPurse: 8000
  },
  {
    id: "team-avd-eleven",
    leagueId: "leg-jsl",
    serialNo: 5,
    name: "AVD ELEVEN",
    shortCode: "AVD",
    ownerName: "Apu Ghosh",
    ownerPhone: "9800000005",
    captainName: "Apu Ghosh",
    iconPlayerName: "Rohit Pramanik",
    iconName: "Rohit Pramanik",
    logoUrl: "assets/team_confirm_5_avd_eleven.jpg",
    teamLogoUrl: "assets/team_confirm_5_avd_eleven.jpg",
    registrationStatus: "APPROVED",
    paymentStatus: "APPROVED",
    purse: 8000,
    remainingPurse: 8000
  },
  {
    id: "team-ccc",
    leagueId: "leg-jsl",
    serialNo: 6,
    name: "CCC",
    shortCode: "CCC",
    ownerName: "Sourabh De",
    ownerPhone: "9800000006",
    captainName: "Sourabh De",
    iconPlayerName: "Santanu Sarkar",
    iconName: "Santanu Sarkar",
    mentorName: "Mintu Mondal",
    logoUrl: "assets/team_confirm_6_ccc.jpg",
    teamLogoUrl: "assets/team_confirm_6_ccc.jpg",
    registrationStatus: "APPROVED",
    paymentStatus: "APPROVED",
    purse: 8000,
    remainingPurse: 8000
  },
  {
    id: "team-atrika-friend-xi",
    leagueId: "leg-jsl",
    serialNo: 7,
    name: "ATRIKA & FRIEND X1",
    shortCode: "AF1",
    ownerName: "Kartick Maity",
    ownerPhone: "9800000007",
    captainName: "Kartick Maity",
    iconPlayerName: "Sushanta Mallik",
    iconName: "Sushanta Mallik",
    logoUrl: "assets/team_confirm_7_atrika_friend_xi.jpg",
    teamLogoUrl: "assets/team_confirm_7_atrika_friend_xi.jpg",
    registrationStatus: "APPROVED",
    paymentStatus: "APPROVED",
    purse: 8000,
    remainingPurse: 8000
  }
];

export const INITIAL_PLAYERS = [];
export const INITIAL_FIXTURES = [];
